### ISSUE TITLE
inferringQuery.sjs missing?

### ISSUE THREAD

**Issue by ehennum** [grechaw/semantics-tutorial#2]
On Fedora, Hadoop seems to have finished okay but the resource service installation failed because the inferringQuery.sjs source is missing:

15/04/05 09:11:19 INFO contentpump.LocalJobRunner: Total execution time: 25 sec
Installing the semantic extensions
Warning: Couldn't read data from file "inferringQuery.sjs", this makes an 
Warning: empty POST.
{"errorResponse":{"statusCode":500, "status":"Internal Server Error", "messageCode":"INTERNAL ERROR", "message":"XDMP-MODNOTTEXT: var extensionModule = require(\"/marklogic.rest.resource/inferringQuery -- Module /marklogic.rest.resource/inferringQuery/assets/resource.sjs is not a text document . See the MarkLogic server error log for further detail."}}

**Comment by grechaw** [comment]
It was indeed missing, but has been since updated.
